[email_settings]
server = "smtp.gmail.com"
port = 587
username = "steinar.brandvik.b@gmail.com"
password = "unno airp ktbc wudp"
sender = "steinar.brandvik.b@gmail.com"
to = "example@email.com"
from = "no-reply@gmail.com"
recipients = [
  { "email" = "steinar.brandvik.b@gmail.com"},
  { "email" = "christinhiller87@gmail.com"},
]

[app_settings]
debug = true
